config/routes.rb
Rails.application.routes.draw do

  resources :cidades
  resources :estados
  resources :patrias
  root 'estados#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/estados_por_patria' => 'estados#estados_por_patria'
  get '/cidades_por_estado' => 'estados#cidades_por_estado'
  post '/options' => 'estados#options'
  post '/options' => 'estados#siglas_por_estado'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cidade.rb
class Cidade < ApplicationRecord
 belongs_to :estado
end

app/models/estado.rb
class Estado < ApplicationRecord
   belongs_to :patria
  has_many :cidades   

  def estados_por_patria(patria_id)
    dados = Estado.where(patria_id: params[:patria_id]).first
    estados.collect { |c| [c.nome, c.id] }
    render json: dados.to_json
  end

end

app/models/patria.rb
class Patria < ApplicationRecord
  has_many :estados
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cidades_controller.rb
class CidadesController < ApplicationController
  before_action :set_cidade, only: [:show, :edit, :update, :destroy]

  # GET /cidades
  # GET /cidades.json
  def index
    @cidades = Cidade.all
  end

  # GET /cidades/1
  # GET /cidades/1.json
  def show
  end

  # GET /cidades/new
  def new
    @cidade = Cidade.new
  end

  # GET /cidades/1/edit
  def edit
  end

  # POST /cidades
  # POST /cidades.json
  def create
    @cidade = Cidade.new(cidade_params)

    respond_to do |format|
      if @cidade.save
        format.html { redirect_to @cidade, notice: 'Cidade was successfully created.' }
        format.json { render :show, status: :created, location: @cidade }
      else
        format.html { render :new }
        format.json { render json: @cidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cidades/1
  # PATCH/PUT /cidades/1.json
  def update
    respond_to do |format|
      if @cidade.update(cidade_params)
        format.html { redirect_to @cidade, notice: 'Cidade was successfully updated.' }
        format.json { render :show, status: :ok, location: @cidade }
      else
        format.html { render :edit }
        format.json { render json: @cidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cidades/1
  # DELETE /cidades/1.json
  def destroy
    @cidade.destroy
    respond_to do |format|
      format.html { redirect_to cidades_url, notice: 'Cidade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def cidades_por_estado
    dados = Cidade.where(estado_id: params[:estado_id]).all
    render json: dados.to_json
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cidade
      @cidade = Cidade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cidade_params
      params.require(:cidade).permit(:nome, :estado_id)
    end
end

app/controllers/estados_controller.rb
class EstadosController < ApplicationController
  before_action :set_estado, only: [:show, :edit, :update, :destroy]

  # GET /estados
  # GET /estados.json
  def index
    @estados = Estado.all
  end

  # GET /estados/1
  # GET /estados/1.json
  def show
  end

  # GET /estados/new
  def new
    @estado = Estado.new
    preparar_form
    
  end

  # GET /estados/1/edit
  def edit
    estados_por_patria
    preparar_form
  end

  # POST /estados
  # POST /estados.json
  def create
    @estado = Estado.new(estado_params)

    respond_to do |format|
      if @estado.save
        format.html { redirect_to @estado, notice: 'Estado was successfully created.' }
        format.json { render :show, status: :created, location: @estado }
      else
        preparar_form
        estados_por_patria
        format.html { render :new }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estados/1
  # PATCH/PUT /estados/1.json
  def update
    respond_to do |format|
      if @estado.update(estado_params)
        format.html { redirect_to @estado, notice: 'Estado was successfully updated.' }
        format.json { render :show, status: :ok, location: @estado }
      else
        estados_por_patria
        preparar_form
        format.html { render :edit }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estados/1
  # DELETE /estados/1.json
  def destroy
    @estado.destroy
    respond_to do |format|
      format.html { redirect_to estados_url, notice: 'Estado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
   
  def estados_por_patria
      dados = Estado.where(patria_id: params[:patria_id]).all
      render :json => dados.to_json
  end

  def cidades_por_estado
    dados = Cidade.where(estado_id: params[:estado_id]).all
    render :json => dados.to_json
  end

  def siglas_por_estado 
    dados = Estado.where(estado_id: params[:estado_id]).all
    render :json => dados.to_json
  end
 
  def options
     id = params[:id]
     @subsigla = Estado.where(:sigla_id => id)
     render :partial => 'options'
end

  private
    
    # Use callbacks to share common setup or constraints between actions.
    def set_estado
      @estado = Estado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estado_params
      params.require(:estado).permit(:nome, :sigla, :patria_id)
    end
    def preparar_form
      @patrias = Patria.order :nome
    end
end

app/controllers/patrias_controller.rb
class PatriasController < ApplicationController
  before_action :set_patria, only: [:show, :edit, :update, :destroy]

  # GET /patrias
  # GET /patrias.json
  def index
    @patrias = Patria.all
  end

  # GET /patrias/1
  # GET /patrias/1.json
  def show
  end

  # GET /patrias/new
  def new
    @patria = Patria.new
  end

  # GET /patrias/1/edit
  def edit
  end

  # POST /patrias
  # POST /patrias.json
  def create
    @patria = Patria.new(patria_params)

    respond_to do |format|
      if @patria.save
        format.html { redirect_to @patria, notice: 'Patria was successfully created.' }
        format.json { render :show, status: :created, location: @patria }
      else
        format.html { render :new }
        format.json { render json: @patria.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patrias/1
  # PATCH/PUT /patrias/1.json
  def update
    respond_to do |format|
      if @patria.update(patria_params)
        format.html { redirect_to @patria, notice: 'Patria was successfully updated.' }
        format.json { render :show, status: :ok, location: @patria }
      else
        format.html { render :edit }
        format.json { render json: @patria.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patrias/1
  # DELETE /patrias/1.json
  def destroy
    @patria.destroy
    respond_to do |format|
      format.html { redirect_to patrias_url, notice: 'Patria was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  

  private

    def estadoss_por_patria
      dados = Estado.where(patria_id: params[:patria_id]).all
      render json: dados.to_json
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_patria
      @patria = Patria.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patria_params
      params.require(:patria).permit(:nome, :sigla)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cidades_helper.rb
module CidadesHelper
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/helpers/patrias_helper.rb
module PatriasHelper
end

app/views/cidades/_form.html.erb
<%= form_for(cidade) do |f| %>
  <% if cidade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cidade.errors.count, "error") %> prohibited this cidade from being saved:</h2>

      <ul>
      <% cidade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field">
    <%= f.label :estado_id %>
    <%= f.number_field :estado_id %>
  </div>


  <div class="field">
    <%= f.label :nome %>
     <select id="cidade_id" name="cidade_id" class="form-control">
              <option>Selecione um estado...</option>
            </select>
  </div>

 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<script>
  // evento change do select
  // toda vez que um item do select é clicado, o evento change é disparado
  $('#estado_id').on('change', function() {

    // ao disparar o evento change, conseguimos pegar o valor do item selecionado
    $.ajax({
      // fazemos uma chamada ajax para a rota rails passando como parâmetro o estado selecionado
      url: "/cidades_por_estado?estado_id=" + this.value
    }).done(function(result) {
      // assim que a chamada ajax terminar, podemos montar o select de cidades

      // atualiza o primeiro item do select de cidades
      $("#cidade_id option:first").text("Selecione");

      // percorre cada cidade e adiciona no select de cidades
      for (var i = 0; i < result.length; i++) {
        // adiciona cada didade no select através de um option
        $('#cidade_id').append($("<option></option>").attr("value", result[i].id).text(result[i].nome)); // => <option value='1'>Cidade</option>
      }
    });
  });
</script>

app/views/cidades/edit.html.erb
<h1>Editing Cidade</h1>

<%= render 'form', cidade: @cidade %>

<%= link_to 'Show', @cidade %> |
<%= link_to 'Back', cidades_path %>

app/views/cidades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cidades</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cidades.each do |cidade| %>
      <tr>
        <td><%= cidade.nome %></td>
        <td><%= cidade.estado_id %></td>
        <td><%= link_to 'Show', cidade %></td>
        <td><%= link_to 'Edit', edit_cidade_path(cidade) %></td>
        <td><%= link_to 'Destroy', cidade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cidade', new_cidade_path %>

app/views/cidades/new.html.erb
<h1>New Cidade</h1>

<%= render 'form', cidade: @cidade %>

<%= link_to 'Back', cidades_path %>

app/views/cidades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @cidade.nome %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @cidade.estado_id %>
</p>

<%= link_to 'Edit', edit_cidade_path(@cidade) %> |
<%= link_to 'Back', cidades_path %>

app/views/estados/_form.html.erb
<%= form_for(estado, remote: true) do |f| %>
  <% if estado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(estado.errors.count, "error") %> prohibited this estado from being saved:</h2>

      <ul>
      <% estado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :País %>
        <%= collection_select(:patria ,:id, Patria.all, :id, :nome, :include_blank => 'SELECT A COUNTRY') %>

  </div>

  <div class="field">
    <label for="estado">Estado</label>
    <!-- COMBO DE ESTADO VAZIA ESPERANDO PARA SER POPULADA -->
    <select id="estado_id" name="state" class="form-control" style="width: 200px">
      <option>Selecione um estado...</option>
    </select>
  </div>
  <div class="field">
    <%= f.label :sigla %>
    <%= f.text_field :sigla, :class => 'form-control', :style=>"width: 200px"  %>
  </div>
  
  <div class="field">
    <label for="estado">Estado</label>
    <!-- COMBO DE ESTADO VAZIA ESPERANDO PARA SER POPULADA -->
    <select id="cidade_id" name="state" class="form-control" style="width: 200px">
      <option>Selecione uma cidade...</option>
    </select>
  </div>
 
  

  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<script>
  // evento change do select
  // toda vez que um item do select é clicado, o evento change é disparado
  $('#patria_id').on('change', function() {

    // ao disparar o evento change, conseguimos pegar o valor do item selecionado
    $.ajax({
      // fazemos uma chamada ajax para a rota rails passando como parâmetro o estado selecionado
      url: "/estados_por_patria?patria_id=" + this.value
    }).done(function(result) {
      // assim que a chamada ajax terminar, podemos montar o select de cidades

      // atualiza o primeiro item do select de estados
      $("#estado_id option:first").text("Selecione Estado");

      // percorre cada estado e adiciona no select de estados
      for (var i = 0; i < result.length; i++) {
        // adiciona cada didade no select através de um option
        $('#estado_id').append($("<option></option>").attr("value", result[i].id).text(result[i].nome)); // => <option value='1'>Estado</option>
      }
    });
  });
</script>


<script>
  // Buscar cidades...
  // evento change do select
  // toda vez que um item do select é clicado, o evento change é disparado
  $('#estado_id').on('change', function() {

    // ao disparar o evento change, conseguimos pegar o valor do item selecionado
    $.ajax({
      // fazemos uma chamada ajax para a rota rails passando como parâmetro o estado selecionado
      url: "/cidades_por_estado?estado_id=" + this.value
    }).done(function(result) {
      // assim que a chamada ajax terminar, podemos montar o select de cidades

      // atualiza o primeiro item do select de cidades
      $("#cidade_id option:first").text("Selecione");

      // percorre cada cidade e adiciona no select de cidades
      for (var i = 0; i < result.length; i++) {
        // adiciona cada didade no select através de um option
        $('#cidade_id').append($("<option></option>").attr("value", result[i].id).text(result[i].nome)); // => <option value='1'>Cidade</option>
      }
    });
  });
</script>

<script>
  // evento change do select
  // toda vez que um item do select é clicado, o evento change é disparado
  $('#patria_id').on('change', function() {

    // ao disparar o evento change, conseguimos pegar o valor do item selecionado
    $.ajax({
      // fazemos uma chamada ajax para a rota rails passando como parâmetro o estado selecionado
      url: "/siglas_por_estado?patria_id=" + this.value
    }).done(function(result) {
      // assim que a chamada ajax terminar, podemos montar o select de pratos
      $('#patria_id option[value!="0"]').remove();
      // atualiza o primeiro item do select de cidades
      $("#patria_id option:first").text("Selecione");

      // percorre cada cidade e adiciona no select de cidades
      for (var i = 0; i < result.length; i++) {
        // adiciona cada didade no select através de um option
        $('#estado_id').append($("<option></option>").attr("value", result[i].id).text(result[i].sigla)); // => <option value='1'>pRATO</option>
        $('#estado_sigla').append($("<option></option>").attr("value", result[i].id).text(result[i].sigla)); // => <option value='1'>pRATO</option>
      }
    });
  });
</script>



<script>
$(document).ready(function(){
   $('#sigla_id').change(function(){
       var value = $(this).val()
       $.ajax({
          type: 'POST',
          url: 'options',
          data: {id: value},
          success: function(data){
            $('#subsigla').html(data)
          }
       })
   })
})
</script>

app/views/estados/edit.html.erb
<h1>Editing Estado</h1>

<%= render 'form', estado: @estado %>

<%= link_to 'Show', @estado %> |
<%= link_to 'Back', estados_path %>

app/views/estados/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Estados</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Sigla</th>
      <th>Patria</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estados.each do |estado| %>
      <tr>
        <td><%= estado.nome %></td>
        <td><%= estado.sigla %></td>
        <td><%= estado.patria_id %></td>
        <td><%= link_to 'Show', estado %></td>
        <td><%= link_to 'Edit', edit_estado_path(estado) %></td>
        <td><%= link_to 'Destroy', estado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Estado', new_estado_path %>

app/views/estados/new.html.erb
<h1>New Estado</h1>

<%= render 'form', estado: @estado %>

<%= link_to 'Back', estados_path %>

app/views/estados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @estado.nome %>
</p>

<p>
  <strong>Sigla:</strong>
  <%= @estado.sigla %>
</p>

<p>
  <strong>Patria:</strong>
  <%= @estado.patria.nome %>
</p>

<%= link_to 'Edit', edit_estado_path(@estado) %> |
<%= link_to 'Back', estados_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EstadoCidades</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- CHAMADAS EXTERNAS PARA O BOOTSTRAP E JQUERY -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <script   src="https://code.jquery.com/jquery-2.2.3.min.js"   integrity="sha256-a23g1Nt4dtEYOj7bR+vTu7+T8VP13humZFBJNIYoEJo="   crossorigin="anonymous"></script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/patrias/_form.html.erb
<%= form_for(patria) do |f| %>
  <% if patria.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patria.errors.count, "error") %> prohibited this patria from being saved:</h2>

      <ul>
      <% patria.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label :sigla %>
    <%= f.text_field :sigla %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patrias/edit.html.erb
<h1>Editing Patria</h1>

<%= render 'form', patria: @patria %>

<%= link_to 'Show', @patria %> |
<%= link_to 'Back', patrias_path %>

app/views/patrias/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Patrias</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Sigla</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patrias.each do |patria| %>
      <tr>
        <td><%= patria.nome %></td>
        <td><%= patria.sigla %></td>
        <td><%= link_to 'Show', patria %></td>
        <td><%= link_to 'Edit', edit_patria_path(patria) %></td>
        <td><%= link_to 'Destroy', patria, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patria', new_patria_path %>

app/views/patrias/new.html.erb
<h1>New Patria</h1>

<%= render 'form', patria: @patria %>

<%= link_to 'Back', patrias_path %>

app/views/patrias/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @patria.nome %>
</p>

<p>
  <strong>Sigla:</strong>
  <%= @patria.sigla %>
</p>

<%= link_to 'Edit', edit_patria_path(@patria) %> |
<%= link_to 'Back', patrias_path %>